# Generated by Django 5.0.7 on 2024-08-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(choices=[('PG', 'Разыгрывающий защитник'), ('SG', 'Атакующий защитник'), ('SF', 'Легкий форвард'), ('PF', 'Мощный форвард'), ('C', 'Центровой')], max_length=2),
        ),
    ]
