# Generated by Django 5.0.7 on 2024-08-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_players_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leagues',
            new_name='league',
        ),
        migrations.RenameModel(
            old_name='matches',
            new_name='match',
        ),
        migrations.RenameModel(
            old_name='players',
            new_name='player',
        ),
        migrations.RenameModel(
            old_name='player_stats',
            new_name='player_statistic',
        ),
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
        migrations.RenameModel(
            old_name='team_stats',
            new_name='team_statistic',
        ),
    ]
