# Generated by Django 5.0.7 on 2024-08-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_leagues_league_rename_matches_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='login',
        ),
    ]
